project:
  type: website

bibliography: bibliography.bib

website:
  title: "GATAS Laboratory | University of Florida"
  favicon: _assets/brand/favicon.ico
  navbar:
    logo: _assets/gatas_logo.png
    collapse-below: sm
    right:
      - members.qmd
      - projects.qmd
      - research.qmd
      - text: "AMMA"
        href: amma.qmd
      - text: "Blog"
        href: https://blog.algebraicjulia.org/
      - icon: github
        href: https://github.com/AlgebraicJulia
      - icon: favicon.ico
        href: https://www.algebraicjulia.org/
format:
  html:
    html-math-method: katex
    theme:
      light: flatly
      dark: darkly
    linkcolor: "#4E8ABB" 
    navbar:
      background: "#4E8ABB"
      foreground: "#6FB450"
    # Blue: "#4E8ABB" 
    # Green: "#6FB450"
    # Orange: "#6FB450"
    css: styles.css
    monofont: JuliaMono-Regular

from: markdown+tex_math_single_backslash
