project:
  type: website

bibliography: bibliography.bib

website:
  title: "GATAS Lab, University Florida"
  favicon: _assets/brand/favicon.ico
  navbar:
    logo: _assets/brand/logo-darkbg.svg
    collapse-below: sm
    right:
      - text: "Blog"
        href: https://blog.algebraicjulia.org/
      - about.qmd
      - members.qmd
      - seminars.qmd
      - icon: github
        href: https://github.com/AlgebraicJulia
      - icon: favicon.ico
        href: https://www.algebraicjulia.org/
format:
  html:
    html-math-method: katex
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    monofont: JuliaMono-Regular

from: markdown+tex_math_single_backslash
