---
title: Members
listing: 
  - id: members
    contents: 
      - members/jamesfairbanks.qmd
      - members/benbumpus.qmd
      - members/wilmerleal.qmd
      - members/lukemorris.qmd
      - members/tylerhanks.qmd
      - members/richardsamuelson.qmd
      - members/cuffaromatt.qmd
      - members/georgerauta.qmd
      - members/samuelcohen.qmd
      - members/trevorgross.qmd

    type: default
    image-align: left
    image-height: 250px
    sort: false
  - id: mentoring
    contents: 
      - members/mentoring.yaml
    type: table
    # image-height: 250px
    sort: "Year desc"
    fields: [Name, Degree, Company, Dates]
    field-display-names: 
      Degree: "Program"
      Company: "Last Known Institution"
---

The members of the lab come from diverse perspectives with unique training. We are always looking for students and researchers with a desire to solve problems by leveraging abstract applications in novel science and engineering applications.

Accepting Applications for 

* PhD Students in both [CISE](https://www.cise.ufl.edu/academics/graduate/phd/) and [MAE](https://mae.ufl.edu/students/graduate/degree-programs-requirements/). Mathematically minded students would benefit from the MAE degree program specializing in Dynamics, Systems, and Control.
  - For MAE applicants, the GATAS lab is particularly well suited to students interested in either Dynamics, Systems, and Control for [optimization and dynamics projects](project/optimization.qmd) or Computational Fluid Dynamics (CFD) for the [Decapodes project](project/decapodes.qmd).
  - For CISE students, the GATAS lab is a good fit for students interested in High Performance Computing (HPC), Machine Learning, Data Science, Applied and Computational Mathematics, Computer Algebra, and Programming Language Theory.

* Research Projects for Undergraduates and Graduate Students in CISE, MAE, and Math

* Research Scientists and Postdocs in CISE, MAE, Math

*Email fairbanksj [at] ufl [dot] edu for all new position inquiries*

If you are interested in a career in Applied Category Theory or Computational Science and Engineering, please reach out. 

## Current Members

:::{#members}
:::

## Past Members

|  Name | Where are they now?|
|:------|:-------------------|
|James Horn      |Master's Student at Georgia Tech        |
|Kris Brown      |Research Software Engineer at the Topos Institute|
|Micah Halter    |Research Scientist at the Georgia Tech Research Institute|
|Caroline Rogers |Industry|
|Rebecca Boes    |Industry|
|James Eschrich  |PhD Student at University of Illinois (UIUC) |
|Taylor Frederick|Industry|
|Patrick Stokes  |GatorSense Lab at UF ECE|

## Lab Mentees

These are people who might not have spent full-time employment in the lab, but were involved in a mentorship program or ongoing mentoring relationship outside beyond the institution.

:::{#mentoring}
:::
