---
title: "Research"
---

## Software

### [Decapodes.jl](https://algebraicjulia.github.io/Decapodes.jl/stable/)

Decapodes are a graphical tool for the composition of physical systems.     
Ultimately, this library will include tooling which takes advantage of the formalization of physical theories described by DEC provided by CombinatorialSpaces.jl.

Links:

- [Journal of Computational Science](publications/jocs.md)

### [AlgebraicControl.jl](https://github.com/AlgebraicJulia/AlgebraicControl.jl.git)

Model predictive control (MPC) is an optimal control technique which involves 
solving a sequence of constrained optimization problems across a given time horizon.
We present a novel Julia library that leverages our theoretical results to automate 
the implementation of correct-by-construction MPC problems in software. 

## Preprints

| Year | Title |
| ---- | ----- |
| 2024 | [The diagrammatic presentation of equations in categories](https://arxiv.org/abs/2401.09751) <br> Kevin Arlin, James Fairbanks, Tim Hosgood, and Evan Patterson |
| 2024 | [Towards a Compositional Framework for Convex Analysis](https://arxiv.org/abs/2312.02291) <br> Richard Samuelson and Dario Stein |
| 2023 | [A Compositional Framework for Convex Model Predictive Control](https://arxiv.org/abs/2305.03820) <br> Tyler Hanks, Baike She, Matthew Hale, Evan Patterson, Matthew Klawonn, and James Fairbanks |
| 2023 | [Characterizing Compositionality of LQR from the Categorical Perspective](https://arxiv.org/abs/2305.01811) <br> Baike She, Tyler Hanks, James Fairbanks, and Matthew Hale |
| 2023 | [Compositional Algorithms on Compositional Data: Deciding Sheaves on Presheaves](https://arxiv.org/abs/2302.05575) <br> Ernst Althaus, Benjamin Merlin Bumpus, James Fairbanks, and Daniel Rosiak |
| 2023 | [A compositional account of motifs, mechanisms, and dynamics in biochemical regulatory networks](https://arxiv.org/abs/2301.01445) <br> Rebekah Aduddell, James Fairbanks, Amit Kumar, Pablo Ocal, Evan Patterson, and Brandon Shapiro |

## Journal Papers

| Year | Title |
| ---- | ----- |
| 2023 | [Computational category-theoretic rewriting](https://www.sciencedirect.com/science/article/abs/pii/S2352220823000421) <br> Kristopher Brown, Evan Patterson, Tyler Hanks, and James Fairbanks <br> [Journal of Logical and Algebraic Methods in Programming](https://www.sciencedirect.com/journal/journal-of-logical-and-algebraic-methods-in-programming) |
| 2023 | [The application of applied category theory to quantify mission success](https://journals.sagepub.com/doi/abs/10.1177/00375497221114861) <br> Robert K Garrett, James Fairbanks, Margaret Loper, and James Moreland <br> [Simulation](https://journals.sagepub.com/home/SIM) |
| 2022 | [An algebraic framework for structured epidemic modelling](https://royalsocietypublishing.org/doi/full/10.1098/rsta.2021.0309) <br> Sophie Libkind, Andrew Baas, Micah Halter, Evan Patterson, and James Fairbanks <br> [Philosophical Transactions of the Royal Society A](https://royalsocietypublishing.org/journal/rsta) |
| 2022 | [A diagrammatic view of differential equations in physics](http://www.aimspress.com/article/doi/10.3934/mine.2023036) <br> Evan Patterson, Andrew Baas, Timothy Hosgood, and James Fairbanks <br> [Mathematics in Engineering](http://www.aimspress.com/journal/mine) |
| 2021 | [Categorical Data Structures for Technical Computing](https://compositionality-journal.org/papers/compositionality-4-5/) <br> Evan Patterson, Owen Lynch, and James Fairbanks <br> [Compositionality](https://compositionality-journal.org) |
| 2021 | [Category-Theoretic Formulation of the Model-Based Systems Architecting Cognitive-Computational Cycle](https://www.mdpi.com/2076-3417/11/4/1945) <br> Yaniv Mordecai, James Fairbanks, and Edward Crawley <br> [Applied Sciences](https://www.mdpi.com/journal/applsci) | 

## Conference Papers

| Year | Title |
| ---- | ----- |
| 2023 | [A Categorical Representation Language and Computational System for Knowledge-Based Robotic Task Planning](https://ojs.aaai.org/index.php/AAAI-SS/article/view/27718) <br> Angeline Aguinaldo, Evan Patterson, James Fairbanks, William Regli, and Jaime Ruiz <br> [2023 AAAI Fall Symposium on Unifying Representations for Robot Application Development](https://sites.google.com/view/aaai-ur-rad-symposium/home) |
| 2022 | [Compositional Exploration of Combinatorial Scientific Models](https://msp.cis.strath.ac.uk/act2022/papers/ACT2022_paper_2062.pdf) <br> Kristopher Brown, Tyler Hanks, and James Fairbanks <br> [5th International Conference on Applied Category Theory](https://msp.cis.strath.ac.uk/act2022/index.html) |
| 2022 | [Computational Category-Theoretic Rewriting](https://link.springer.com/chapter/10.1007/978-3-031-09843-7_9) <br> Kristopher Brown, Evan Patterson, Tyler Hanks, and James Fairbanks <br> [15th International Conference on Graph Transformation](https://icgt2022.gitlab.io) |
| 2021 | [Operadic Modeling of Dynamical Systems: Mathematics and Computation](https://arxiv.org/abs/2105.12282v3) <br> Sophie Libkind, Andrew Baas, Evan Patterson, and James Fairbanks <br> [4th International Conference on Applied Category Theory](https://www.cl.cam.ac.uk/events/act2021/) |
